name: Build

on:
  push:
    branches:
      - "tmp/*"
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup node
      #   uses: actions/setup-node@v1

      # - name: Build
      #   run: |
      #     yarn --fronzen-lockfile
      #     yarn build
      #     ./build.sh

      - name: Check secret
        run: |
          echo ${{ github.ref }}
          jq --version
          curl https://thatcopy.pw/catapi/rest
          echo "secret is ${{ secret.API_URL }}"
          curl https://${{ secret.API_URL }}
